### ISSUE TITLE
The winner loses money instead of gaining it

### ISSUE THREAD

**Issue by RmbRT** [peer3to/state-channels-plus#1]
I tested it out on peer3.to and it seems like the winner loses 50 instead of gaining 50.

**Comment by lukastanisic99** [comment]
Can you try again and provide a screenshot?

Your account (balance) is always in the top left - the opponent is top right.

Also note that after a round concludes, if you were X you become O for the next round and vice versa.

If something is confusing in the UI, let us know so we can change it.

Tanssi (the blockchain provider thought which the demo is inheriting security from Polkadot) had problems yesterday with their nodes, but this shouldn't affect the problem you're describing since it's not related to opening/disputing the channel (which happens on-chain)

**Comment by RmbRT** [comment]
ah, yeah, then I did not notice the top-left balance. I only noticed the top right corner balance.
